In [2]:
# special IPython command to prepare the notebook for matplotlib
import matplotlib.pyplot as plt

#Array processing
import numpy as np
#Data analysis, wrangling and common exploratory operations
import pandas as pd
from pandas import Series, DataFrame
from itertools import chain
import datetime
#For visualization. Matplotlib for basic viz and seaborn for more stylish figures
# import matplotlib.pyplot as plt
import seaborn as snscx

In [3]:
#read the csv file into a Pandas data frame
df_data = pd.read_csv('Gender_classifier.csv', encoding='latin1')
df_data

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
0,815719226,False,finalized,3,10/26/15 23:24,male,1.0000,yes,1.0,12/5/13 01:48,...,https://pbs.twimg.com/profile_images/414342229...,0,FFFFFF,Robbie E Responds To Critics After Win Against...,NaN,110964,10/26/15 12:40,6.590000e+17,main; @Kan1shk3,Chennai
1,815719227,False,finalized,3,10/26/15 23:30,male,1.0000,yes,1.0,10/1/12 13:51,...,https://pbs.twimg.com/profile_images/539604221...,0,C0DEED,ÛÏIt felt like they were my friends and I was...,NaN,7471,10/26/15 12:40,6.590000e+17,NaN,Eastern Time (US & Canada)
2,815719228,False,finalized,3,10/26/15 23:33,male,0.6625,yes,1.0,11/28/14 11:30,...,https://pbs.twimg.com/profile_images/657330418...,1,C0DEED,i absolutely adore when louis starts the songs...,NaN,5617,10/26/15 12:40,6.590000e+17,clcncl,Belgrade
3,815719229,False,finalized,3,10/26/15 23:10,male,1.0000,yes,1.0,6/11/09 22:39,...,https://pbs.twimg.com/profile_images/259703936...,0,C0DEED,Hi @JordanSpieth - Looking at the url - do you...,NaN,1693,10/26/15 12:40,6.590000e+17,"Palo Alto, CA",Pacific Time (US & Canada)
4,815719230,False,finalized,3,10/27/15 01:15,female,1.0000,yes,1.0,4/16/14 13:23,...,https://pbs.twimg.com/profile_images/564094871...,0,0,Watching Neighbours on Sky+ catching up with t...,NaN,31462,10/26/15 12:40,6.590000e+17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20045,815757572,True,golden,259,NaN,female,1.0000,yes,1.0,8/5/15 21:16,...,https://pbs.twimg.com/profile_images/656793310...,0,C0DEED,"@lookupondeath ...Fine, and I'll drink tea too...",NaN,783,10/26/15 13:20,6.590000e+17,Verona ªÁ,NaN
20046,815757681,True,golden,248,NaN,male,1.0000,yes,1.0,8/15/12 21:17,...,https://pbs.twimg.com/profile_images/639815429...,0,0,Greg Hardy you a good player and all but don't...,NaN,13523,10/26/15 12:40,6.590000e+17,"Kansas City, MO",NaN
20047,815757830,True,golden,264,NaN,male,1.0000,yes,1.0,9/3/12 01:17,...,https://pbs.twimg.com/profile_images/655473271...,0,C0DEED,You can miss people and still never want to se...,NaN,26419,10/26/15 13:20,6.590000e+17,Lagos Nigeria,NaN
20048,815757921,True,golden,250,NaN,female,0.8489,yes,1.0,11/6/12 23:46,...,https://pbs.twimg.com/profile_images/657716093...,0,0,@bitemyapp i had noticed your tendency to pee ...,NaN,56073,10/26/15 12:40,6.590000e+17,Texas Hill Country,NaN
20049,815757985,True,golden,249,NaN,female,1.0000,yes,1.0,4/14/14 17:22,...,https://pbs.twimg.com/profile_images/655134724...,0,C0DEED,I think for my APUSH creative project I'm goin...,NaN,2922,10/26/15 13:19,6.590000e+17,NaN,NaN

In [4]:
df = pd.read_csv('Gender_classifier.csv', encoding='latin1', usecols=['gender'])
s = df.gender
counts = s.value_counts()
counts

female     6700
male       6194
brand      5942
unknown    1117
Other        97
Name: gender, dtype: int64

In [5]:
# df_f = pd.DataFrame(df_data)
# print (df_f)

In [6]:
topSevenRecords = df_data.head(7)
topSevenRecords

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
0,815719226,False,finalized,3,10/26/15 23:24,male,1.0000,yes,1.0,12/5/13 01:48,...,https://pbs.twimg.com/profile_images/414342229...,0,FFFFFF,Robbie E Responds To Critics After Win Against...,NaN,110964,10/26/15 12:40,6.590000e+17,main; @Kan1shk3,Chennai
1,815719227,False,finalized,3,10/26/15 23:30,male,1.0000,yes,1.0,10/1/12 13:51,...,https://pbs.twimg.com/profile_images/539604221...,0,C0DEED,ÛÏIt felt like they were my friends and I was...,NaN,7471,10/26/15 12:40,6.590000e+17,NaN,Eastern Time (US & Canada)
2,815719228,False,finalized,3,10/26/15 23:33,male,0.6625,yes,1.0,11/28/14 11:30,...,https://pbs.twimg.com/profile_images/657330418...,1,C0DEED,i absolutely adore when louis starts the songs...,NaN,5617,10/26/15 12:40,6.590000e+17,clcncl,Belgrade
3,815719229,False,finalized,3,10/26/15 23:10,male,1.0000,yes,1.0,6/11/09 22:39,...,https://pbs.twimg.com/profile_images/259703936...,0,C0DEED,Hi @JordanSpieth - Looking at the url - do you...,NaN,1693,10/26/15 12:40,6.590000e+17,"Palo Alto, CA",Pacific Time (US & Canada)
4,815719230,False,finalized,3,10/27/15 01:15,female,1.0000,yes,1.0,4/16/14 13:23,...,https://pbs.twimg.com/profile_images/564094871...,0,0,Watching Neighbours on Sky+ catching up with t...,NaN,31462,10/26/15 12:40,6.590000e+17,NaN,NaN
5,815719231,False,finalized,3,10/27/15 01:47,female,1.0000,yes,1.0,3/11/10 18:14,...,https://pbs.twimg.com/profile_images/656336865...,0,0,"Ive seen people on the train with lamps, chair...",NaN,20036,10/26/15 12:40,6.590000e+17,New York Gritty,Central Time (US & Canada)
6,815719232,False,finalized,3,10/27/15 01:57,brand,1.0000,yes,1.0,4/24/08 13:03,...,https://pbs.twimg.com/profile_images/528547133...,0,0,@BpackEngineer Thank you for your patience whi...,NaN,13354,10/26/15 12:40,6.590000e+17,Worldwide,Eastern Time (US & Canada)

In [7]:
bottomSevenRecords = df_data.tail(7)
bottomSevenRecords

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
20043,815756700,True,golden,240,NaN,male,1.0000,yes,1.0,9/27/11 00:19,...,https://pbs.twimg.com/profile_images/378800000...,1,5ED4DC,"Game faggot and venison loin, crisp spelt and ...",NaN,8193,10/26/15 13:19,6.590000e+17,Chertsey Bridge,NaN
20044,815756767,True,golden,227,NaN,female,1.0000,yes,1.0,6/11/14 01:55,...,https://pbs.twimg.com/profile_images/643483977...,0,C0DEED,Need A Ride Home From Practice _Ù÷Ô_Ù÷Ô_Ù÷ÔAnd...,NaN,6669,10/26/15 13:19,6.590000e+17,NaN,NaN
20045,815757572,True,golden,259,NaN,female,1.0000,yes,1.0,8/5/15 21:16,...,https://pbs.twimg.com/profile_images/656793310...,0,C0DEED,"@lookupondeath ...Fine, and I'll drink tea too...",NaN,783,10/26/15 13:20,6.590000e+17,Verona ªÁ,NaN
20046,815757681,True,golden,248,NaN,male,1.0000,yes,1.0,8/15/12 21:17,...,https://pbs.twimg.com/profile_images/639815429...,0,0,Greg Hardy you a good player and all but don't...,NaN,13523,10/26/15 12:40,6.590000e+17,"Kansas City, MO",NaN
20047,815757830,True,golden,264,NaN,male,1.0000,yes,1.0,9/3/12 01:17,...,https://pbs.twimg.com/profile_images/655473271...,0,C0DEED,You can miss people and still never want to se...,NaN,26419,10/26/15 13:20,6.590000e+17,Lagos Nigeria,NaN
20048,815757921,True,golden,250,NaN,female,0.8489,yes,1.0,11/6/12 23:46,...,https://pbs.twimg.com/profile_images/657716093...,0,0,@bitemyapp i had noticed your tendency to pee ...,NaN,56073,10/26/15 12:40,6.590000e+17,Texas Hill Country,NaN
20049,815757985,True,golden,249,NaN,female,1.0000,yes,1.0,4/14/14 17:22,...,https://pbs.twimg.com/profile_images/655134724...,0,C0DEED,I think for my APUSH creative project I'm goin...,NaN,2922,10/26/15 13:19,6.590000e+17,NaN,NaN

In [8]:
df_data.head(7).append(df_data.tail(7))

/var/folders/z4/fkls1k917_51fhgf9jbrkgd40000gn/T/ipykernel_1311/1364191184.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_data.head(7).append(df_data.tail(7))

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
0,815719226,False,finalized,3,10/26/15 23:24,male,1.0000,yes,1.0,12/5/13 01:48,...,https://pbs.twimg.com/profile_images/414342229...,0,FFFFFF,Robbie E Responds To Critics After Win Against...,NaN,110964,10/26/15 12:40,6.590000e+17,main; @Kan1shk3,Chennai
1,815719227,False,finalized,3,10/26/15 23:30,male,1.0000,yes,1.0,10/1/12 13:51,...,https://pbs.twimg.com/profile_images/539604221...,0,C0DEED,ÛÏIt felt like they were my friends and I was...,NaN,7471,10/26/15 12:40,6.590000e+17,NaN,Eastern Time (US & Canada)
2,815719228,False,finalized,3,10/26/15 23:33,male,0.6625,yes,1.0,11/28/14 11:30,...,https://pbs.twimg.com/profile_images/657330418...,1,C0DEED,i absolutely adore when louis starts the songs...,NaN,5617,10/26/15 12:40,6.590000e+17,clcncl,Belgrade
3,815719229,False,finalized,3,10/26/15 23:10,male,1.0000,yes,1.0,6/11/09 22:39,...,https://pbs.twimg.com/profile_images/259703936...,0,C0DEED,Hi @JordanSpieth - Looking at the url - do you...,NaN,1693,10/26/15 12:40,6.590000e+17,"Palo Alto, CA",Pacific Time (US & Canada)
4,815719230,False,finalized,3,10/27/15 01:15,female,1.0000,yes,1.0,4/16/14 13:23,...,https://pbs.twimg.com/profile_images/564094871...,0,0,Watching Neighbours on Sky+ catching up with t...,NaN,31462,10/26/15 12:40,6.590000e+17,NaN,NaN
5,815719231,False,finalized,3,10/27/15 01:47,female,1.0000,yes,1.0,3/11/10 18:14,...,https://pbs.twimg.com/profile_images/656336865...,0,0,"Ive seen people on the train with lamps, chair...",NaN,20036,10/26/15 12:40,6.590000e+17,New York Gritty,Central Time (US & Canada)
6,815719232,False,finalized,3,10/27/15 01:57,brand,1.0000,yes,1.0,4/24/08 13:03,...,https://pbs.twimg.com/profile_images/528547133...,0,0,@BpackEngineer Thank you for your patience whi...,NaN,13354,10/26/15 12:40,6.590000e+17,Worldwide,Eastern Time (US & Canada)
20043,815756700,True,golden,240,NaN,male,1.0000,yes,1.0,9/27/11 00:19,...,https://pbs.twimg.com/profile_images/378800000...,1,5ED4DC,"Game faggot and venison loin, crisp spelt and ...",NaN,8193,10/26/15 13:19,6.590000e+17,Chertsey Bridge,NaN
20044,815756767,True,golden,227,NaN,female,1.0000,yes,1.0,6/11/14 01:55,...,https://pbs.twimg.com/profile_images/643483977...,0,C0DEED,Need A Ride Home From Practice _Ù÷Ô_Ù÷Ô_Ù÷ÔAnd...,NaN,6669,10/26/15 13:19,6.590000e+17,NaN,NaN
20045,815757572,True,golden,259,NaN,female,1.0000,yes,1.0,8/5/15 21:16,...,https://pbs.twimg.com/profile_images/656793310...,0,C0DEED,"@lookupondeath ...Fine, and I'll drink tea too...",NaN,783,10/26/15 13:20,6.590000e+17,Verona ªÁ,NaN
20046,815757681,True,golden,248,NaN,male,1.0000,yes,1.0,8/15/12 21:17,...,https://pbs.twimg.com/profile_images/639815429...,0,0,Greg Hardy you a good player and all but don't...,NaN,13523,10/26/15 12:40,6.590000e+17,"Kansas City, MO",NaN
20047,815757830,True,golden,264,NaN,male,1.0000,yes,1.0,9/3/12 01:17,...,https://pbs.twimg.com/profile_images/655473271...,0,C0DEED,You can miss people and still never want to se...,NaN,26419,10/26/15 13:20,6.590000e+17,Lagos Nigeria,NaN
20048,815757921,True,golden,250,NaN,female,0.8489,yes,1.0,11/6/12 23:46,...,https://pbs.twimg.com/profile_images/657716093...,0,0,@bitemyapp i had noticed your tendency to pee ...,NaN,56073,10/26/15 12:40,6.590000e+17,Texas Hill Country,NaN
20049,815757985,True,golden,249,NaN,female,1.0000,yes,1.0,4/14/14 17:22,...,https://pbs.twimg.com/profile_images/655134724...,0,C0DEED,I think for my APUSH creative project I'm goin...,NaN,2922,10/26/15 13:19,6.590000e+17,NaN,NaN

In [9]:
df_data.dtypes

_unit_id                   int64
_golden                     bool
_unit_state               object
_trusted_judgments         int64
_last_judgment_at         object
gender                    object
gender:confidence        float64
profile_yn                object
profile_yn:confidence    float64
created                   object
description               object
fav_number                 int64
gender_gold               object
link_color                object
name                      object
profile_yn_gold           object
profileimage              object
retweet_count              int64
sidebar_color             object
text                      object
tweet_coord               object
tweet_count                int64
tweet_created             object
tweet_id                 float64
tweet_location            object
user_timezone             object
dtype: object

In [10]:
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
train, validate, test = \
              np.split(df_data.sample(frac=1, random_state=42), 
                       [int(.6*len(df_data)), int(.8*len(df_data))])

In [ ]:
train

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
15589,815735081,False,finalized,3,10/26/2015 23:44,female,1.0000,yes,1.0,8/24/2013 3:48,...,https://pbs.twimg.com/profile_images/598891740...,0,C0DEED,@ladscheckups I've applied for the 31st Octobe...,NaN,4742,10/26/2015 13:19,6.590000e+17,NaN,Vienna
18801,815738369,False,finalized,3,10/26/2015 23:04,brand,1.0000,yes,1.0,4/23/2015 0:23,...,https://pbs.twimg.com/profile_images/591140429...,0,C0DEED,#raspberry #tech #pi - Raspbian Û¢ Re: How to...,NaN,55727,10/26/2015 13:19,6.590000e+17,NaN,Belgrade
15905,815735406,False,finalized,3,10/26/2015 23:06,female,1.0000,yes,1.0,7/27/2009 12:37,...,https://pbs.twimg.com/profile_images/643878914...,0,F2E195,I couldn't feel anymore like a stereotype toda...,NaN,4203,10/26/2015 13:19,6.590000e+17,NaN,Quito
4720,815724023,False,finalized,3,10/27/2015 0:56,brand,1.0000,yes,1.0,5/28/2009 11:40,...,https://pbs.twimg.com/profile_images/268024980...,0,FF5703,Photo: Official news from @lovelandskiarea Shr...,NaN,3433,10/26/2015 12:40,6.590000e+17,"iPhone: 40.016956,-105.279739",Mountain Time (US & Canada)
4885,815724191,False,finalized,3,10/26/2015 23:05,male,1.0000,yes,1.0,5/5/2012 11:11,...,https://pbs.twimg.com/profile_images/586960186...,0,C0DEED,@BostonRavenFans @RussellStReport go watch the...,NaN,6003,10/26/2015 12:40,6.590000e+17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8719,815728053,False,finalized,3,10/27/2015 0:58,brand,0.6838,yes,1.0,3/2/2015 3:26,...,https://pbs.twimg.com/profile_images/613893635...,0,C0DEED,BUY MARIJUANA SEEDS: Who is switching on the M...,NaN,45326,10/26/2015 12:39,6.590000e+17,"Manchester, England",Pacific Time (US & Canada)
14399,815733862,False,finalized,3,10/26/2015 22:02,male,0.6691,yes,1.0,8/11/2008 7:05,...,https://pbs.twimg.com/profile_images/632599817...,0,002D7A,And that's my Halloween costume sorted!,NaN,7976,10/26/2015 13:19,6.590000e+17,"Sheffield, England",London
13624,815733072,False,finalized,3,10/27/2015 1:05,brand,1.0000,yes,1.0,1/13/2010 13:24,...,https://pbs.twimg.com/profile_images/629374027...,0,DFDFDF,Check latest auction - Penthouse Pet ASHLEY RO...,NaN,4262,10/26/2015 13:20,6.590000e+17,CA,Pacific Time (US & Canada)
8146,815727468,False,finalized,3,10/27/2015 1:27,female,1.0000,yes,1.0,11/1/2012 6:43,...,https://pbs.twimg.com/profile_images/658707493...,0,EEEEEE,"hi @Harry_Styles ,thank you for being\nso nice...",NaN,95350,10/26/2015 12:39,6.590000e+17,Turkey,Europe/Athens
7968,815727290,False,finalized,3,10/26/2015 23:53,brand,1.0000,yes,1.0,8/7/2014 13:46,...,https://abs.twimg.com/sticky/default_profile_i...,0,C0DEED,Get Weather Updates from The Weather Channel. ...,NaN,69303,10/26/2015 12:40,6.590000e+17,NaN,NaN

In [ ]:
test

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
18280,815737833,False,finalized,3,10/26/2015 23:37,brand,1.0000,yes,1.0,7/22/2010 23:49,...,https://pbs.twimg.com/profile_images/594044254...,0,829D5E,Are you a fan of #starwars check this out http...,NaN,2308,10/26/2015 13:19,6.590000e+17,"Newcastle, Australia",Sydney
2617,815721911,False,finalized,3,10/26/2015 23:37,male,0.6517,yes,1.0,3/31/2012 12:44,...,https://pbs.twimg.com/profile_images/378800000...,0,FFFFFF,1 tweep unfollowed (goodbye!) me in the past d...,NaN,11902,10/26/2015 12:40,6.590000e+17,AL-MADINAH,Riyadh
2411,815721703,False,finalized,3,10/27/2015 1:44,male,0.6741,yes,1.0,12/2/2009 9:55,...,https://pbs.twimg.com/profile_images/108111021...,0,C0DEED,@tmbrntt by the front door,NaN,1773,10/26/2015 12:40,6.590000e+17,London,London
1094,815720327,False,finalized,3,10/26/2015 22:53,female,1.0000,yes,1.0,1/27/2014 9:09,...,https://pbs.twimg.com/profile_images/658722145...,0,C0DEED,doctors think you got all the time in the worl...,NaN,6552,10/26/2015 12:40,6.590000e+17,cloud9,Eastern Time (US & Canada)
6065,815725375,False,finalized,3,10/27/2015 1:52,unknown,0.3537,yes,1.0,5/8/2013 9:04,...,https://pbs.twimg.com/profile_images/604806305...,0,C0DEED,"Quote of the day - ""bye:/""",NaN,2780,10/26/2015 12:40,6.590000e+17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,815730665,False,finalized,3,10/26/2015 22:01,female,1.0000,yes,1.0,12/9/2011 6:20,...,https://pbs.twimg.com/profile_images/454633168...,0,0,To Serrena in Washington. Serrena is 14 and ha...,NaN,10999,10/26/2015 13:20,6.590000e+17,"Vancouver Island, BC",Alaska
11964,815731365,False,finalized,3,10/26/2015 23:16,female,1.0000,yes,1.0,1/16/2012 19:06,...,https://pbs.twimg.com/profile_images/658036461...,0,65B0DA,When you're sick and your dog loves you bunche...,NaN,15500,10/26/2015 13:20,6.590000e+17,"Wander or roam, TN is home.",Atlantic Time (Canada)
5390,815724698,False,finalized,3,10/27/2015 1:48,brand,1.0000,yes,1.0,2/19/2009 16:34,...,https://pbs.twimg.com/profile_images/238634656...,0,339103,@Sara_Valor Thanks for the mention!,NaN,22675,10/26/2015 12:40,6.590000e+17,USA,Central Time (US & Canada)
860,815720089,False,finalized,3,10/26/2015 21:58,brand,1.0000,yes,1.0,9/22/2015 13:58,...,https://pbs.twimg.com/profile_images/656559747...,0,0,https://t.co/ayr4C6eAZx\n\nIn the studio Recor...,NaN,352,10/26/2015 12:40,6.590000e+17,"Los Angeles, CA",NaN
15795,815735291,False,finalized,3,10/27/2015 1:28,brand,1.0000,yes,1.0,9/4/2009 11:32,...,https://pbs.twimg.com/profile_images/346128699...,0,0,"Gil is talking to Rick Klien, from @ABC, about...",NaN,9939,10/26/2015 13:19,6.590000e+17,SF / Bay Area,Pacific Time (US & Canada)

In [ ]:
validate

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,gender,gender:confidence,profile_yn,profile_yn:confidence,created,...,profileimage,retweet_count,sidebar_color,text,tweet_coord,tweet_count,tweet_created,tweet_id,tweet_location,user_timezone
4264,815723563,False,finalized,3,10/26/2015 23:50,brand,0.6730,yes,1.0,6/15/2014 11:12,...,https://abs.twimg.com/sticky/default_profile_i...,0,C0DEED,Get Weather Updates from The Weather Channel. ...,NaN,36760,10/26/2015 12:40,6.590000e+17,NaN,NaN
19894,815739489,False,finalized,3,10/26/2015 22:26,male,0.6414,yes,1.0,8/11/2013 12:26,...,https://pbs.twimg.com/profile_images/658653892...,0,BDDCAD,2 followers and 20 unfollowers ok,NaN,65359,10/26/2015 13:18,6.590000e+17,universe,Ljubljana
10652,815730019,False,finalized,3,10/27/2015 0:19,brand,1.0000,yes,1.0,12/15/2011 14:26,...,https://pbs.twimg.com/profile_images/613432894...,0,C0DEED,Fancy being a Ball Sponsor this Saturday? Just...,NaN,5886,10/26/2015 13:20,6.590000e+17,"St James' Park, Alnwick.",London
6825,815726140,False,finalized,3,10/26/2015 22:38,brand,1.0000,yes,1.0,7/2/2013 3:02,...,https://pbs.twimg.com/profile_images/649179515...,0,EEEEEE,Could the new strike force of Ameobi and Heske...,NaN,19756,10/26/2015 12:40,6.590000e+17,London,NaN
8113,815727435,False,finalized,3,10/27/2015 1:22,brand,0.6675,yes,1.0,4/12/2015 23:31,...,https://abs.twimg.com/sticky/default_profile_i...,0,C0DEED,Get Weather Updates from The Weather Channel. ...,NaN,31308,10/26/2015 12:39,6.590000e+17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2775,815722069,False,finalized,3,10/27/2015 1:16,brand,0.6696,yes,1.0,1/18/2012 12:38,...,https://pbs.twimg.com/profile_images/464226495...,0,0,#MegaWeen @vivo_lounge\nThis Thursday the 2015...,"[40.7288513, -74.1581802]",6135,10/26/2015 12:40,6.590000e+17,NaN,Arizona
17167,815736693,False,finalized,3,10/27/2015 1:24,brand,1.0000,yes,1.0,9/29/2015 20:31,...,https://pbs.twimg.com/profile_images/650735918...,0,C0DEED,HALLOWEEN CLUB TONIGHT!!! BYOF (bring your own...,NaN,15,10/26/2015 13:19,6.590000e+17,"Roanoke, VA",NaN
4145,815723444,False,finalized,3,10/27/2015 0:00,male,1.0000,yes,1.0,7/17/2009 12:31,...,https://pbs.twimg.com/profile_images/328011061...,0,FFFFFF,Sounding like my rules interpretation was wron...,NaN,27188,10/26/2015 12:40,6.590000e+17,"Boise, ID",Mountain Time (US & Canada)
10515,815729882,False,finalized,3,10/26/2015 22:17,female,1.0000,yes,1.0,3/20/2012 12:43,...,https://pbs.twimg.com/profile_images/649700693...,0,65B0DA,"look awful &amp; drained, but love this photo,...","[64.1333, -21.9333]",47258,10/26/2015 13:20,6.590000e+17,essex. || hopefulÏ¬,Amsterdam
8954,815728292,False,finalized,3,10/26/2015 23:49,brand,1.0000,yes,1.0,1/22/2012 10:32,...,https://pbs.twimg.com/profile_images/586974924...,0,FFFFFF,We've heard the requests of students to be all...,NaN,2286,10/26/2015 12:39,6.590000e+17,Bloemfontein,Athens

In [ ]:
y = df_data.iloc[:,4].values
y

array(['10/26/2015 23:24', '10/26/2015 23:30', '10/26/2015 23:33', ...,
       nan, nan, nan], dtype=object)